#!/bin/sh
modlist=$1
newval=$2
tmp=$(mktemp)

len="$(cat $modlist | jq ".mods | length")"
done=false

for i in $(seq 0 $(( len - 1 ))); do
	mod="$(cat $modlist | jq -r ".mods[$i].name")"
	if [ "$mod" = "fotograf" ]; then
		cat $modlist | jq ".mods[$i].enabled = $newval" > $tmp
		mv $modlist $modlist.orig
		mv $tmp $modlist
		done=true
	fi
done

if [ "$done" = false ]; then
	cat $modlist | jq ".mods[$len] = {\"name\": \"fotograf\", \"enabled\": $newval}" > $tmp
	mv $modlist $modlist.orig
	mv $tmp $modlist
fi

