#!/bin/sh
cfiles=`find src -type f -name \*.[ch]`
webfiles=`find src/web -type f`
luafiles=`find src/fotograf -type f -name \*.lua.asset`

echo -n "C semicolons: "
grep -F ";" $cfiles | wc -l

echo -n "Web LOC: "
cat $webfiles | wc -l

echo -n "Lua LOC: "
cat $luafiles | wc -l

