#!/bin/sh

if [ $# -eq 0 ]
then
	echo "No save name supplied"
	exit 1
fi

# link mod
ln -sf $(pwd)/fotograf_1.0.0 ~/.factorio/mods/ &&

# use our mod list
mv ~/.factorio/mods/mod-list.json ~/.factorio/mods/mod-list.json.backup &&
cp ./mod-list.json ~/.factorio/mods/mod-list.json &&

# load the save and generate the images
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@" &&
echo "Exit the game as soon as you gain control of your character                     " &&
echo "or if any error occurres. In that case you probably entered an invalid save name" &&
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@" &&
factorio --load-game $1 1> /dev/null &&

# make a copy of the web template
mkdir $1 &&
cp ./web/index* $1/ &&

# move the images and map info
mv ~/.factorio/script-output/images/      $1/ &&
mv ~/.factorio/script-output/mapInfo.json $1/ &&

# return original mod list
mv ~/.factorio/mods/mod-list.json.backup ~/.factorio/mods/mod-list.json &&

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@" &&
echo "map was successfully generated (if there was no error in factorio)" &&
echo "generated web is in $(pwd)/$1/" &&
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
