#!/bin/sh
if [ $# -eq 0 ]; then
	echo specify what folder to optimize
	exit 1
fi

find $1 -name "*.png" | parallel --bar "mogrify -quality 40 -format jpg {} && command rm {}"

echo "NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE"
echo "  YOU HAVE TO CHANGE THE 'image_type'       "
echo "  ENTRY IN THE 'map_info.js' FILE TO 'jpg'  "
echo "NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE"

